Account_Modul/urls.py
from django.urls import path
from Account_Modul import views

app_name = 'account_modul'

urlpatterns = [
    path('register',views.RegisterView.as_view(),name="register"),
    path('login',views.LoginView.as_view(),name="login"),
    path('logout',views.LogotView.as_view(),name='logout'),
    path('active_code/<email_active_code>',views.ActivateAccountView.as_view(),name='active_code'),
    path('verify_code',views.Send_Code.as_view(),name='verify_code'),
    path('verify_code/change_password',views.Chanch_Password.as_view(),name='change_password'),
]

Practice/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path ('',include('Home_Modul.urls',namespace='home_modul')),
    path('auth/',include('Account_Modul.urls',namespace='account_modul')),
    path('panel/',include('User_Panel_Modul.urls',namespace='panel')),
    path('contact-us/',include('contact_Modul.urls',namespace='contact-us')),
    path('product/',include('Product.urls',namespace='product')),
    path('about-us/',include('About_Us.urls',namespace='about_us')),
    path('article/',include('Article_Module.urls',namespace='article')),
    path('order/',include('Order_Modul.urls',namespace='order')),
    path('admin/', admin.site.urls),
    
]


if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Product/urls.py
from django.urls import path
from Product import views

app_name = 'products'

urlpatterns = [
    path('',views.ProductListView.as_view(),name='Product_List'),
    path('<slug>',views.DetailView.as_view(),name='example'),
    path('brand/<data>',views.Brand_Filter,name='brand_filter'),
    path('category/<data>',views.Category_Filter,name='category_filter'),
]

templates/Reset_Password/change_password.html
{% extends 'shared/_Layout.html' %}

{% block title %}
    <title>تغییر پسورد</title>
{% endblock %}


{% block content %}
    <div class="container">
        <section id="form"><!--form-->
            <div class="row">
                <div class="col-sm-4 ">
                    <div class="login-form">
                        <form action="{% url 'account_modul:change_password' %}" method="post">
                            {% csrf_token %}
                            

                            <div class="form-group {% if form.errors %} text-danger {% endif %}">
                                {{form.verify_code}}
                                {{form.errors.verify_code}}
                            </div>

                            <div class="form-group">
                                {{form.password}}
                            </div>
                                   
                            <button type="submit">تایید</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

templates/Reset_Password/verify.html
{% extends 'shared/_Layout.html' %}

{% block title %}
    <title>ارسال کد تایید</title>
{% endblock %}


{% block content %}
    <div class="container">
        <section id="form"><!--form-->
            <div class="row">
                <div class="col-sm-4 ">
                    <div class="login-form">
                        <form action="{% url 'account_modul:verify_code' %}" method="post">
                            {% csrf_token %}
                            

                            <div class="form-group {% if form.errors %} text-danger {% endif %}">
                                {{form.user_name}}
                                {{form.errors.user_name}}
                            </div>
                                   
                            <button type="submit">تایید</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}