Order_Modul/urls.py
from django.urls import path
from .views import add_product_to_order,show_order,FinalStepOrder,ShowPaymentInformation


app_name = 'order'

urlpatterns = [
    path('add-to-order',add_product_to_order,name="add_to_order"),
    path('show-order',show_order,name="show_order"),
    path('by-page/',FinalStepOrder.as_view(),name='by_page'),
    path('show-information/<pk>/<int:id>',ShowPaymentInformation.as_view(),name='ShowPaymentInformation')
]

Practice/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path ('',include('Home_Modul.urls',namespace='home_modul')),
    path('auth/',include('Account_Modul.urls',namespace='account_modul')),
    path('panel/',include('User_Panel_Modul.urls',namespace='panel')),
    path('contact-us/',include('contact_Modul.urls',namespace='contact-us')),
    path('product/',include('Product.urls',namespace='product')),
    path('about-us/',include('About_Us.urls',namespace='about_us')),
    path('article/',include('Article_Module.urls',namespace='article')),
    path('order/',include('Order_Modul.urls',namespace='order')),
    path('admin/', admin.site.urls),
    
]


if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Product/urls.py
from django.urls import path
from Product import views

app_name = 'products'

urlpatterns = [
    path('',views.ProductListView.as_view(),name='Product_List'),
    path('<slug>',views.DetailView.as_view(),name='example'),
    path('brand/<data>',views.Brand_Filter,name='brand_filter'),
    path('category/<data>',views.Category_Filter,name='category_filter'),
]

User_Panel_Modul/urls.py
from django.urls import path
from .views import UserPanelView,EditUserInformationView,ChangePasswordView,OrdersView,OrderDetailView
from django.contrib.auth.decorators import login_required


app_name = "panel"

urlpatterns = [
    path('', login_required(UserPanelView.as_view(),login_url='account_modul:login'),name='user_panel'),
    path('edit-profile', login_required(EditUserInformationView.as_view(),login_url='account_modul:login'),name='user_panel_edit'),
    path('order/',OrdersView.as_view(),name='order'),
    path('order/<int:pk>',OrderDetailView.as_view(),name='order_detail'),
    path('edit-password', login_required(ChangePasswordView.as_view(),login_url='account_modul:login'),name='edit_password'),
]

templates/Panel/OrderDetail.html
{% extends 'shared/_Layout.html' %}
{% load render_partial %}
{% load static %}
{% load jalali_tags %}
{% load poll_extras %}

{% block title %}
    <title>تغییر اطلاعات</title>
{% endblock %}


{% block content %}
    <div class="container mt-lg-5" style="direction: rtl !important;">
        <div class="row">
            
            <div class="col-md-4">
                {% render_partial 'User_Panel_Modul.views.componnent_list_group' %}
            </div>  

            <br>
            <br>

            <div class="col-md-8 mt-5">

                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">تصویر</th>
                        <th scope="col">محصول</th>
                        <th scope="col">قیمت</th>
                        <th scope="col">تعداد</th>
                        <th scope="col">قیمت کل</th>
                      </tr>
                    </thead>


                    <tbody>
                        {% for order in orders %}
                        <tr>
                          <th>
                            <img src="{{order.product.image.url}}" width="60px" height="60px" alt="" style="border-radius: 50%;">
                          </th>
                          <td>{{order.product.title}}</td>
                          <td>{{order.product.price|floatformat:"g"}}</td>
                          <td>{{order.count}}</td>
                          <td>{{order.final_price|floatformat:"g"}}</td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <br>
    <br>
{% endblock %}

templates/Panel/Orders.html
{% extends 'shared/_Layout.html' %}
{% load render_partial %}
{% load static %}
{% load jalali_tags %}
{% load poll_extras %}

{% block title %}
    <title>تغییر اطلاعات</title>
{% endblock %}


{% block content %}
    <div class="container mt-lg-5" style="direction: rtl !important;">
        <div class="row">
            
            <div class="col-md-4">
                {% render_partial 'User_Panel_Modul.views.componnent_list_group' %}
            </div>  

            <br>
            <br>

            <div class="col-md-8 mt-5">

                <table class="table table-responsive table-hover table-light">
                    <thead>
                      <tr>
                        <th scope="col" class="text-right">شناسه</th>
                        <th scope="col" class="text-right">قیمت کل</th>
                        <th scope="col" class="text-right">کدهگیری</th>
                        <th scope="col" class="text-right">تاریخ خرید</th>
                      </tr>
                    </thead>


                    <tbody>
                        {% for order in orders %}
                        <tr>
                          <th scope="row" class="text-right"><a href="{% url 'panel:order_detail' pk=order.id %}">{{order.id}}</a></th>
                          <td class="text-right">{{order.total_invoice|floatformat:"g"}}</td>
                          <td class="text-right">{{order.tracking_code}}</td>
                          <td class="text-right">{{order.payment_date|jalali_date}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>


                <nav aria-label="">
                    <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item" style="margin-left: 10px;"><a class="page-link" href="?page={{page_obj.previous_page_number}}">قبلی</a></li>
                    {% endif %}
                    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }} ... {{ page_obj.paginator.num_pages }}</a></li>
                    {% if page_obj.has_next %}
                    <li class="page-item" style="margin-right: 10px;"><a class="page-link" href="?page={{page_obj.next_page_number}}">بعدی</a></li>
                    {% endif %}
                    </ul>
                </nav>


            </div>
        </div>
    </div>
    <br>
    <br>
{% endblock %}

templates/Panel/change_password.html
{% extends 'shared/_Layout.html' %}
{% load render_partial %}
{% load static %}

{% block title %}
    <title>تغییر اطلاعات</title>
{% endblock %}


{% block content %}
    <div class="container mt-lg-5" style="direction: rtl !important;">
        <div class="row">
            
            <div class="col-md-4">
                {% render_partial 'User_Panel_Modul.views.componnent_list_group' %}
            </div>  

            <br>
            <br>

            <div class="col-md-8">
                <form action="{% url 'panel:edit_password' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <br>
                    <div class="form-group {% if form.errors %} text-danger {% endif %}">
                        {{form_data.current_password}}
                        <strong style="color: red !important;">{{form_data.errors.current_password}}</strong>
                    </div>

                    <br>
                    <div class="form-group {% if form.errors %} text-danger {% endif %}">
                        {{form_data.password}}
                        <strong style="color: red !important;">{{form_data.errors.password}}</strong>
                    </div>
                    
                    <br>
                    <div class="form-group {% if form.errors %} text-danger {% endif %}">
                        {{form_data.re_password}}
                        <strong style="color: red !important;">{{form_data.errors.re_password}}</strong>
                    </div>

                    <br>
                    <button class="btn btn-success form-control mt-2">ذخیره</button>
                </form>
            </div>
        </div>
    </div>
    <br>
    <br>
{% endblock %}

templates/Panel/componnent_list_group.html
 <ul class="list-group text-center">
    <li class="list-group-item"><a href="{% url 'panel:user_panel' %}" style="{% if request.resolver_match.url_name == 'user_panel' %} color: purple; {% endif %}">پنل کاربری</a></li>
    <li class="list-group-item"><a href="{% url 'panel:user_panel_edit' %}" style="{% if request.resolver_match.url_name == 'user_panel_edit' %} color: purple; {% endif %}">ویرایش اطلاعات</a></li>
    <li class="list-group-item"><a href="{% url 'panel:order' %}" style="{% if request.resolver_match.url_name == 'order' %} color: purple; {% endif %}">سفارشات</a></li>
    <li class="list-group-item"><a href="{% url 'panel:edit_password' %}" style="{% if request.resolver_match.url_name == 'edit_password' %} color: purple; {% endif %}">تغییر رمز</a></li>
</ul>

templates/Panel/editprofile.html
{% extends 'shared/_Layout.html' %}
{% load render_partial %}
{% load static %}

{% block title %}
    <title>تغییر اطلاعات</title>
{% endblock %}


{% block content %}
    <div class="container d-flex justify-content-center mt-lg-5" style="direction: rtl !important;">
        <div class="row">
            
            <div class="col-md-4">
                
              
                {% render_partial 'User_Panel_Modul.views.componnent_list_group' %}
            </div>  

            <div class="col-md-8 pull-right" style="direction: rtl !important;">
                <form action="{% url 'panel:user_panel_edit' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                        <br>
                        <div class="row">
                            <div class="col-md-8 mt-lg-5">
                                
                                {{form_edit.avatar.label}}
                                {{form_edit.avatar}}
                                {{form_edit.errors.avatar}}

                                
                            </div>
                            
                            <br>

                            <div class="col-md-4">
                                <br>
                                {% if request.user.avatar %}
                                    <img src="{{request.user.avatar.url}}" alt="" style="width:80%; border-radius: 50% !important;">
                                {% endif %}
                            </div>
                        </div>
                        <br>

                        <div class="row">

                            <div class="col-md-6">
                                <br>
                                {{form_edit.first_name.label}} <span> : </span>
                                {{form_edit.first_name}}
                                {{form_edit.errors.first_name}}
                            </div>

                            <div class="col-md-6">
                                <br>
                                {{form_edit.last_name.label}} <span> : </span>
                                {{form_edit.last_name}}
                                {{form_edit.errors.last_name}}
                            </div>

                        </div>
                        <br>

                        {{form_edit.about_user.label}} <span> : </span>
                        {{form_edit.about_user}}
                        {{form_edit.errors.about_user}}

                        <br>

                        {{form_edit.address.label}} <span> : </span>
                        {{form_edit.address}}
                        {{form_edit.errors.address}}

                        <br>


                        <div class="row">

                            <div class="col-md-6">
                                <br>
                                {{form_edit.postalـcode.label}} <span> : </span>
                                {{form_edit.postalـcode}}
                                {{form_edit.errors.postalـcode}}
                            </div>

                            <div class="col-md-6">
                                <br>
                                {{form_edit.phone.label}} <span> : </span>
                                {{form_edit.phone}}
                                {{form_edit.errors.phone}}
                            </div>

                        </div>
                        <br>

                        <div class="row">

                            <div class="col-md-6">
                                <br>
                                {{form_edit.instagram_account.label}} <span> : </span>
                                {{form_edit.instagram_account}}
                                {{form_edit.errors.instagram_account}}
                            </div>

                            <div class="col-md-6">
                                <br>
                                {{form_edit.twitter_account.label}} <span> : </span>
                                {{form_edit.twitter_account}}
                                {{form_edit.errors.twitter_account}}
                            </div>

                        </div>
                        <br>

                        <div class="row">

                            <div class="col-md-6">
                                <br>
                                {{form_edit.facbook_account.label}} <span> : </span>
                                {{form_edit.facbook_account}}
                                {{form_edit.errors.facbook_account}}
                            </div>

                            <div class="col-md-6">
                                <br>
                                {{form_edit.linkedin_account.label}} <span> : </span>
                                {{form_edit.linkedin_account}}
                                {{form_edit.errors.linkedin_account}}
                            </div>

                        </div>

                    <br>
                    <button class="btn btn-success form-control">ذخیره</button>
                </form>
            </div>
        </div>
    </div>
    <br>
    <br>
{% endblock %}

templates/Panel/user_panel.html
{% extends 'shared/_Layout.html' %}
{% load render_partial %}
{% load static %}
{% load thumbnail %}
{% block title %}
    <title>{{data}}</title>
{% endblock %}


{% block content %}
        <div class="container mt-lg-5" style="direction: rtl !important;">
            <div class="row">
    
                <div class="col-lg-4 col-md-4">
                    {% render_partial 'User_Panel_Modul.views.componnent_list_group' %}
                    <br>
                </div>
                
                
                <div class="col-lg-8 col-md-8 mt-lg-5">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row">

                                <div class="col-md-6">
                                    <h6><b>نام کاربری</b><span> : </span> {{data.username}}</h6>
                                    <h6><b>نام</b><span> : </span>{{data.first_name}}</h6>
                                    <h6><b>نام خانوادگی</b><span> : </span>{{data.last_name}}</h6>
                                    <h6><b>موبایل</b><span> : </span>{{data.phone}}</h6>
                                    <h6><b>کد پستی</b><span> : </span>{{data.postalـcode}}</h6>
                                    <h6><b>ایمیل</b><span> : </span>{{data.email}}</h6>
                                    
                                    <div class="mt-4 d-flex justify-content-between" style="font-size: medium !important;">
                                        {% if data.instagram_account %}
                                            <a href="//{{data.instagram_account}}"><i class='bx bxl-instagram-alt'></i></a>
                                        {% endif %}

                                        {% if data.facbook_account %}
                                            <a href="//{{data.facbook_account}}"><i class='bx bxl-facebook-circle'></i></a>
                                        {% endif %}

                                        {% if data.twitter_account %}
                                            <a href="//{{data.twitter_account}}"><i class='bx bxl-twitter'></i></a>
                                        {% endif %}

                                        {% if data.linkedin_account %}
                                            <a href="//{{data.linkedin_account}}"><i class='bx bxl-linkedin' ></i></a>
                                        {% endif %}
                                    </div>
                                    
                                </div>

                                <div class="col-md-6">
                                    {% thumbnail data.avatar "200x200" quality=100 as im %}
                                        <img style="border-radius: 50% !important;" src="{{ im.url }}">
                                    {% endthumbnail %}
                                    
                                </div>

                                <br>
                                
                            </div>
                        </div>

                        <hr class="w-25">

                        <div class="col-lg-12">
                            <h6><b>توضیحات</b><span> : </span></h6>{{data.about_user}}
                            <br>
                        </div>

                        <hr class="w-25">


                        <div class="col-lg-12">
                            <h6><b>آدرس</b><span> : </span></h6>{{data.address}}
                            <br>
                        </div>

                        <hr class="w-25">

                        <div class="col-lg-12">
                            <h6><b>کد تایید</b><span> : </span></h6>{{data.email_active_code}}
                        </div>
                    </div>
                </div>
    
            </div>
        </div>
        <br>
        <br>

   
{% endblock %}