About_Us/urls.py
from django.urls import path
from About_Us import views

app_name = "about_us"

urlpatterns = [
    path('',views.AboutUsView.as_view(),name='about_us')
]

Account_Modul/urls.py
from django.urls import path
from Account_Modul import views

app_name = 'account_modul'

urlpatterns = [
    path('register',views.RegisterView.as_view(),name="register"),
    path('login',views.LoginView.as_view(),name="login"),
    path('logout',views.LogotView.as_view(),name='logout'),
    path('active_code/<email_active_code>',views.ActivateAccountView.as_view(),name='active_code'),
    path('verify_code',views.Send_Code.as_view(),name='verify_code'),
    path('verify_code/change_password',views.Chanch_Password.as_view(),name='change_password'),
]

Home_Modul/urls.py
from django.urls import path
from Home_Modul import views

app_name = 'home_modul'

urlpatterns = [
    path('',views.HomeView.as_view(),name="home"),

]

Order_Modul/urls.py
from django.urls import path
from .views import add_product_to_order,show_order,FinalStepOrder,ShowPaymentInformation


app_name = 'order'

urlpatterns = [
    path('add-to-order',add_product_to_order,name="add_to_order"),
    path('show-order',show_order,name="show_order"),
    path('by-page/',FinalStepOrder.as_view(),name='by_page'),
    path('show-information/<pk>/<int:id>',ShowPaymentInformation.as_view(),name='ShowPaymentInformation')
]

Practice/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path ('',include('Home_Modul.urls',namespace='home_modul')),
    path('auth/',include('Account_Modul.urls',namespace='account_modul')),
    path('panel/',include('User_Panel_Modul.urls',namespace='panel')),
    path('contact-us/',include('contact_Modul.urls',namespace='contact-us')),
    path('product/',include('Product.urls',namespace='product')),
    path('about-us/',include('About_Us.urls',namespace='about_us')),
    path('article/',include('Article_Module.urls',namespace='article')),
    path('order/',include('Order_Modul.urls',namespace='order')),
    path('admin/', admin.site.urls),
    
]


if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Product/urls.py
from django.urls import path
from Product import views

app_name = 'products'

urlpatterns = [
    path('',views.ProductListView.as_view(),name='Product_List'),
    path('<slug>',views.DetailView.as_view(),name='example'),
    path('brand/<data>',views.Brand_Filter,name='brand_filter'),
    path('category/<data>',views.Category_Filter,name='category_filter'),
]

templates/shared/Footer.html
<footer id="footer">
   <div class="container">
     <div class="copyright">
       &copy;<strong><span>{{site_data.copy_right}}</span></strong>
     </div>
     <div class="credits">
       Designed by <span>{{site_data.email}}</span></a>
     </div>
   </div>
 </footer>
 

templates/shared/Header.html
{% load thumbnail %}



<!-- ======= Header ======= -->
<header id="header">
  <div class="d-flex flex-column">

    <div class="profile">
      {% thumbnail data.site_logo "700x700" quality=100 as im %}
        <img src="{{im.url}}" width="50px" height="120px" alt="" style="border-radius: 50% !important;">
      {% endthumbnail %}

      <h1 class="text-light"><a href="{{data.sitr_url}}">{{data.site_name}}</a></h1>
      
      {% if request.user.is_authenticated %}
        <br>
        <div style="text-align: center !important; align-items: center !important;">
          <div class="dropdown">
            <li class=" dropdown-toggle" style="color: white;" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
              {{request.user.username}}
            </li>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
              <li><button class="dropdown-item" type="button"><a href="{% url 'panel:user_panel' %}">حساب کاربری</a></button></li>
              <li><button class="dropdown-item" type="button"><a href="{% url 'account_modul:logout' %}">خروج</a></button></li>
            </ul>
          </div>
        </div>
        <br>
      {% endif %}


      <div class="social-links mt-3 text-center">
        {% for social_links in social_network %}
          <a href="{{social_links.social_network_url}}" class="twitter"><i class="bx bxl-meta"></i></a>
          <span style="font-size: 10px; color: cornsilk;">{{social_links.social_network_name}}</span>
        {% endfor %}
      </div>

    </div>

    <nav id="navbar" class="nav-menu navbar">
      <ul>
        <li><a href="{% url 'home_modul:home' %}" class="nav-link scrollto {% if request.resolver_match.url_name == 'home' %} active {% endif %}"><i class="bx bx-home"></i> <span>Home</span></a></li>
        <li><a href="{% url 'products:Product_List' %}" class="nav-link scrollto {% if request.resolver_match.url_name == 'Product_List' %} active {% endif %}"><i class='bx bx-search-alt'></i> <span>لنز</span></a></li>
        <li><a href="{% url 'products:Product_List' %}" class="nav-link scrollto {% if request.resolver_match.url_name == 'Product_List' %} active {% endif %}"><i class='bx bx-glasses'></i> <span>فریم</span></a></li>
        <li><a href="{% url 'article:articles' %}" class="nav-link scrollto {% if request.resolver_match.url_name == 'articles' %} active {% endif %}"><i class='bx bxs-file-txt'></i> <span>مقالات</span></a></li>

        {% if not request.user.is_authenticated %}
          <li><a href="{% url 'account_modul:login' %}" class="nav-link scrollto {% if request.resolver_match.url_name == 'login' %} active {% endif %}"><i class='bx bx-log-in-circle'></i> <span>ورود</span></a></li>
          <li><a href="{% url 'account_modul:register' %}" class="nav-link scrollto {% if request.resolver_match.url_name == 'register' %} active {% endif %}"><i class='bx bxs-check-shield'></i> <span>ثبت نام</span></a></li>
        {% else %}
       
          <li><a href="{% url 'order:show_order' %}" class="nav-link scrollto {% if request.resolver_match.url_name == 'show_order' %} active {% endif %}"> <i class='bx bx-cart'></i> <span>سبد خرید</span></a></li>
          <li><a href="{% url 'about_us:about_us' %}" class="nav-link scrollto {% if request.resolver_match.url_name == 'about_us' %} active {% endif %}"><i class='bx bxs-medal'></i> <span>درباره ما</span></a></li>
          <li><a href="{% url 'contact-us:contact_us' %}" class="nav-link scrollto {% if request.resolver_match.url_name == 'contact_us' %} active {% endif %}"><i class='bx bxs-message-rounded'></i> <span>ارتباط با ما</span></a></li>
        {% endif %}
      </ul>
    </nav><!-- .nav-menu -->
  </div>
</header>

templates/shared/_Footer.html
{% load static %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script src="{% static 'New_Template/vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static 'New_Template/vendor/aos/aos.js' %}"></script>
<script src="{% static 'New_Template/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'New_Template/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'New_Template/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'New_Template/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'New_Template/vendor/typed.js/typed.min.js' %}"></script>
<script src="{% static 'New_Template/vendor/waypoints/noframework.waypoints.js' %}"></script>
<script src="{% static 'New_Template/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'New_Template/js/main.js' %}"></script>

templates/shared/_Header.html
{% load static %}
    

  

  <link href="{% static 'New_Template/img/favicon.png' %}" rel="icon">
  <link href="{% static 'New_Template/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
  <link href="{% static 'New_Template/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'New_Template/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'New_Template/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'New_Template/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'New_Template/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'New_Template/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'New_Template/css/style.css' %}" rel="stylesheet">

templates/shared/_Layout.html
{% load render_partial %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    {% block title %}
    {% endblock %}


    {% block css %}
    {% endblock %}

    <!-- میتونیم یک سری اطلاعات وارد کنیم -->
    {% include 'shared/_Header.html' %}
</head><!--/head-->

<body>
    <i class="bi bi-list mobile-nav-toggle d-xl-none" style="right: 4px !important;"></i>
    {% render_partial 'Home_Modul.views.sit_header_component' %} 

    <main id="main">
        {% block content %}
        {% endblock %}
    </main>
        
	

    {% render_partial 'Home_Modul.views.sit_footer_component' %} 

    {% include 'shared/_Footer.html' %}
</body>
</html>

templates/shared/grouping.html
<div class="col-sm-3">
    <div class="left-sidebar">

    

        <h2>دسته بندی محصولات</h2>
        <div class="panel-group category-products" id="accordian"><!--category-productsr-->
            
            {% for product_category in product_categorys %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {% if product_category.parents.all  %} 
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordian" href="#{{product_category.url_title}}">
                                    <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                    <a href="{{product_category.get_absolute_url}}">{{product_category.title_fa}}</a>
                                </a>
                            </h4>
                        {% else %}
                            <h4 class="panel-title">
                                <a href="{{product_category.get_absolute_url}}">
                                    {{product_category.title_fa}}
                                </a>
                            </h4>
                        {% endif %}
                    </div>
                    
                    {% if product_category.parents.all %}
                        <div id="{{product_category.url_title}}" class="panel-collapse collapse">
                            <div class="panel-body">
                                
                                <ul>
                                    {% for item in product_category.parents.all %}
                                    
                                        <li><a href="{{item.get_absolute_url}}">{{item.title_fa}}</a></li>
                                
                                    {% endfor %}
                                </ul>
                                
                            </div>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}

            
        </div>








        <div class="brands_products"><!--brands_products-->
            <h2>برنـد ها</h2>
            <div class="brands-name">
                <ul class="nav nav-pills nav-stacked">
                    {% for data in brand %}
                        <li><a href="{{data.get_absolute_url}}"> <span class="pull-left">{{data.product_count}}</span>{{data.title}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div><!--/brands_products-->
        
        <div class="price-range"><!--price-range-->
            <h2>فیلتـر قیمـت</h2>
            <div class="well">
                 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="1000000" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
                 <b>1.000.000 ريال</b> <b class="pull-left">0 ريال</b>
            </div>
        </div><!--/price-range-->

        
    </div>
</div>