Account_Modul/urls.py
from django.urls import path
from Account_Modul import views

app_name = 'account_modul'

urlpatterns = [
    path('register',views.RegisterView.as_view(),name="register"),
    path('login',views.LoginView.as_view(),name="login"),
    path('logout',views.LogotView.as_view(),name='logout'),
    path('active_code/<email_active_code>',views.ActivateAccountView.as_view(),name='active_code'),
    path('verify_code',views.Send_Code.as_view(),name='verify_code'),
    path('verify_code/change_password',views.Chanch_Password.as_view(),name='change_password'),
]

Article_Module/urls.py
from django.urls import path
from Article_Module import views

app_name = "article"

urlpatterns = [
    path('',views.ArticleListView.as_view(),name="articles"),
    path('category/<category>',views.ArticleListView.as_view(),name="articles_category"),
    path('<pk>/<slug>',views.ArticleDetailView.as_view(),name="articles_detail")

]

Practice/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path ('',include('Home_Modul.urls',namespace='home_modul')),
    path('auth/',include('Account_Modul.urls',namespace='account_modul')),
    path('panel/',include('User_Panel_Modul.urls',namespace='panel')),
    path('contact-us/',include('contact_Modul.urls',namespace='contact-us')),
    path('product/',include('Product.urls',namespace='product')),
    path('about-us/',include('About_Us.urls',namespace='about_us')),
    path('article/',include('Article_Module.urls',namespace='article')),
    path('order/',include('Order_Modul.urls',namespace='order')),
    path('admin/', admin.site.urls),
    
]


if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Product/urls.py
from django.urls import path
from Product import views

app_name = 'products'

urlpatterns = [
    path('',views.ProductListView.as_view(),name='Product_List'),
    path('<slug>',views.DetailView.as_view(),name='example'),
    path('brand/<data>',views.Brand_Filter,name='brand_filter'),
    path('category/<data>',views.Category_Filter,name='category_filter'),
]

templates/Article/article_detail.html
{% extends 'shared/_Layout.html' %}
{% load static %}
{% load jalali_tags %}
{% load poll_extras %}
{% load thumbnail %}



{% block title %}
    <title>{{Articles.title}}</title>
{% endblock %}

{% block content %}
    <div class="container" style="direction: rtl !important;">
        <div class="row">
            <div class="col-lg-12 col-md-12" style="margin-top: 15px;">
                <div class="col-12">
                    <div class="card" style="border-radius: 15px 15px 0 0; box-shadow: -2px 3px 25px -14px rgba(96, 96, 96, 0.5);">
                        {% if Articles.image %}
                        
                            {% thumbnail Articles.image "862x398" quality=100 crop="center" as im %}
                                <img src="{{im.url}}" class="card-img-top" alt="..." style="border-radius: 15px 15px 0 0 !important;height: 450px;">
                            {% endthumbnail %}
                        {% else %}
                            <img src="" class="card-img-top" alt="..." style="border-radius: 15px 15px 0 0 !important;height: 450px;">
                        {% endif %}
                        
            
            
                        <div class="card-body">
                            <h3>{{Articles.title}}</h3>
                                
                            <p><i class="bx bx-user " style="color: chocolate;"></i>{{Articles.author}}<span>  </span><i class="bx bx-calendar" style="color: chocolate;"></i> {{ Articles.date_create|jalali_date}}<span>  </span><i class="bx bx-alarm" style="color: chocolate;"></i>{{ Articles.date_create|to_jalali:'%H:%M:%S'}}</p>
            
                            <p>{{Articles.short_description}}</p>
                            <p>{{Articles.text}}</p>

                            <div class="rating-area">
                                برچسب :
                                    
                                    {% for item in Articles.selected_categories.all %}
                                        <a class="color" href="{% url 'article:articles_category' category=item.url_title %}">{{item.title}}<span>/</span></a>
                                    {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
                <br>                    
            </div>

            <div class="col-lg-12">

                <div class="row">

                    <div class="col-lg-2">
                        {% thumbnail Articles.author.avatar "100x100" quality=100 crop="center" as im %}
                            <img class="pull-right" style="border-radius: 50%;" src="{{ im.url }}">
                        {% endthumbnail %}
                    </div>

                    <div class="col-lg-10">
                        <div class="media-body">
                            <h4 class="media-heading">{{Articles.author.first_name}} <span>{{Article.author.last_name}}</span></h4>
                            <p>{{Articles.author.about_user}}</p>
                            <div class="blog-socials" style="text-align: center !important;align-items: center !important;">
                                {% if Articles.author.instagram_account %}
                                    <a href="//{{Articles.author.instagram_account}}"><i class="bx bxl-instagram"></i></a>
                                {% endif %}
    
                                {% if Articles.author.twitter_account %}
                                    <a href="//{{Articles.author.twitter_account}}"><i class="bx bxl-twitter"></i></a>
                                {% endif %}
    
                                {% if Articles.author.facbook_account %}
                                    <a href="//{{Articles.author.facbook_account}}"><i class="bx bxl-facebook"></i></a>
                                {% endif %}
    
                                {% if Articles.author.linkedin_account %}
                                    <a href="//{{Articles.author.linkedin_account}}"><i class="bx bxl-linkedin"></i></a>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            
        </div>

        <div>
            <h2> نطرات  ({{comments.count}})</h2>
            <hr style="color: aqua;" class="w-25">
        </div>

        <br>
            <div class="row">
                <div class="col-lg-12">
                    {% for comment in comments %}
                        <ul class="media-list" id="comment">
                            <div class="row" style="border-radius: 15px 15px 0 0; box-shadow: -2px 3px 25px -14px rgba(96, 96, 96, 0.5);">
                                <div class="col-lg-10">
                                    <br>
                                    <div class="media">
                                        <a class="pull-right" href="">  
                                            {% if comment.user.avatar %}
                                                {% thumbnail comment.user.avatar "60x60" quality=100 crop="center" as im %}
                                                    <img class="media-object" style="border-radius: 50%;" src="{{ im.url }}">
                                                {% endthumbnail %}
                                            {% else %}
                                                <img class="media-object" src="{% static 'images/User/user.png' %}" alt="">
                                            {% endif %}
                                        </a> 
            
                                        <div class="media-body">
                                            <p><i class="bx bx-user " style="color: rgb(127, 228, 206);"></i>{{comment.user}}<span>  </span><i class="bx bx-calendar" style="color: rgb(127, 228, 206);"></i> {{ comment.create_date|jalali_date}}<span>  </span><i class="bx bx-alarm" style="color: rgb(127, 228, 206);"></i>{{ comment.create_date|to_jalali:'%H:%M:%S'}}</p>
                                            <p>{{comment.text}} <span>  </span></p>
                                            
                                            
                                        </div>
            
                                        <br>
                                    </div>
                                </div>
    
                                <div class="col-lg-2" style="text-align: center !important;align-items: center !important; margin-top: 60px !important;margin-bottom: 10 px !important;">
                                    <button class="btn btn-primary" style="border-radius: 150px; margin-right: 50px; margin-bottom: 10px;" onclick="answers({{comment.id}})"><i class="bx bx-reply"></i>پاسـخ</button>
                                </div>

                                <br>


                            {% for com in comment.article_parent.all %}
                                        
                                <div style="padding-right: 60px; border-radius: 15px 15px 0 0; box-shadow: -2px 3px 25px -14px rgba(48, 48, 48, 0.5);">
                                    <div class="media second-media">
                                        <a class="pull-right" href=""> 
                                            <br> 
                                            {% if com.user.avatar %}
                                                {% thumbnail com.user.avatar "60x60" quality=100 crop="center" as im %}
                                                    <img class="media-object" style="border-radius: 50%;" src="{{ im.url }}">
                                                {% endthumbnail %}
                                            {% else %}
                                                <img class="media-object" src="{% static 'images/User/user.png' %}" alt="">
                                            {% endif %}
                                        </a> 
                                        <div class="media-body">
                                            <p><i class="bx bx-user " style="color: rgb(225, 127, 228);"></i>{{com.user}}<span>  </span><i class="bx bx-calendar" style="color: rgb(225, 127, 228);"></i> {{ com.create_date|jalali_date}}<span>  </span><i class="bx bx-alarm" style="color: rgb(225, 127, 228);"></i>{{ com.create_date|to_jalali:'%H:%M:%S'}}</p>
                                            <p>{{com.text}}</p>
                                        </div>
                                    </div>
                                    <br>
                                </div>    

                            {% endfor %}

                            </div>
                            
                            
                            

                        </ul>	
                    {% endfor %}
                </div>
                
            </div>
        <br>

        {% if request.user.is_authenticated %}
                        
            <div class="col-lg-7 ">
                <div style="text-align: center !important; align-items: center !important;">
                    
                </div>

            </div>    

            <div class="row">
                <div class="col-lg-12">
                    <form method="post">
                        {% csrf_token %}
                                        
                                
                        <input type="hidden" name="user"  value="{{request.user.pk}}">
                        <input type="hidden" name="article_id" value="{{Articles.pk}}">
                        <input type="hidden" id="parent_id" name="parentid" value="">
                                    
                        <div class="row">
                            <div class="form-group text-area col-md-10">
                                <div class="blank-arrow" id="answer_comment">
                                    <label>متن پیام</label> 
                                </div>
                                <textarea name="message" id="mes" rows="4" class="w-100"></textarea>
                            </div>

                            <div class="col-md-2" style="text-align: center !important;align-items: center !important; margin-top: 50px !important;">
                                <button class="btn btn-primary" onclick="send_comment()">ارسال نظر</button>
                            </div>
                        </div>
                                    
                        
                       
                        
                    </form>
                </div>
            </div>
            <br>

        {% else %}
            <div class="alert alert-warning">
                برای درج نظـر خود میبایست <a href="{% url 'account_modul:login' %}">لاگین</a> کنید
            </div>
        {% endif %}
        
        <script>

            function send_comment(){
                document.getElementById('comment').scrollIntoView({behavior:"smooth"});
            }

            function answers(parentId){
                document.getElementById('parent_id').value = parentId
                document.getElementById('answer_comment').scrollIntoView({behavior:"smooth"});

            }
        </script>
    </div>

    
{% endblock %}

templates/Article/article_list.html
{% extends 'shared/_Layout.html' %}
{% load static %}
{% load jalali_tags %}
{% load poll_extras %}
{% load render_partial %}
{% load thumbnail %}

{% block title %}
    <title>لیست مقالات</title>
{% endblock %}


{% block content %}
    
    <section id="" class="portfolio">
        <div class="container">

            <div class="row aos-init aos-animate" data-aos="fade-up">
                {% render_partial 'Article_Module.views.grouping_article_component' %} 
            </div>

        
            
            <div style="direction: rtl !important;" class="row">
                {% for article in Articles %}
                    {% include 'include/article_item_component.html' with article=article %}
                {% endfor %}
            </div>
            </div>


            <nav aria-label="Page navigation example" class="mt-5">
                <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">قبلی</a></li>
                {% endif %}
                <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }} ... {{ page_obj.paginator.num_pages }}</a></li>
                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">بعدی</a></li>
                {% endif %}
                </ul>
            </nav>

        </div>
    </section>
    
{% endblock %}






<section>
    <div class="container">


        

        <div class="row">
            
            <div class="col-sm-9">
                <div class="blog-post-area">
                    <h2 class="title text-center">مقالات</h2>

                    {% for article in Articles %}
                        <div class="single-blog-post">
                            <h3>{{article.title}}</h3>
                            <div class="post-meta">
                                <ul>
                                    <li><i class="fa fa-user"></i>{{article.author}}</li>
                                    <li><i class="fa fa-clock-o"></i> {{ article.date_create|jalali_date}}</li>
                                    <li><i class="fa fa-calendar"></i> {{ article.date_create|to_jalali:'%H:%M:%S'}}</li>
                                </ul>
                                <span>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star-half-o"></i>
                                </span>
                            </div>


                            {% thumbnail article.image "862x398" quality=100 crop="center" as im %}
                                <img src="{{ im.url }}">
                            {% endthumbnail %}

                            <br>
                            <br>


                            <p>{{article.short_description}}</p>
                            <a  class="btn btn-primary" href="{{article.get_absolute_url}}">ادامـه مطلب</a>
                        </div>
                    {% endfor %}

                </div>
            </div>
            
            <div class="col-sm-3">
                <div class="left-sidebar">
                    {% render_partial 'Article_Module.views.grouping_article_component' %} 
                </div>
            </div>
            
        </div>
        
    </div>

    
</section>

templates/Article/grouping_article.html
<!-- <div class="panel-group category-products" id="accordian">
    
    {% for article_category in article_categorys %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {% if article_category.parents.all  %} 
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordian" href="#{{article_category.url_title}}">
                            <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                            <a href="{% url 'article:articles_category' category=article_category.url_title %}">{{article_category.title}}</a>
                        </a>
                    </h4>
                {% else %}
                    <h4 class="panel-title">
                        <a href="{% url 'article:articles_category' category=article_category.url_title %}">
                            {{article_category.title}}
                        </a>
                    </h4>
                {% endif %}
            </div>
            
            {% if article_category.parents.all %}
                <div id="{{article_category.url_title}}" class="panel-collapse collapse">
                    <div class="panel-body">
                        
                        <ul>
                            {% for item in article_category.parents.all %}
                            
                                <li><a href="{% url 'article:articles_category' category=item.url_title %}">{{item.title}}</a></li>
                        
                            {% endfor %}
                        </ul>
                        
                    </div>
                </div>
            {% endif %}
        </div>
    {% endfor %}

    
</div> -->


<div class="col-lg-12 d-flex justify-content-center">
    <ul id="portfolio-flters">
        {% for article_category in article_categorys %}
            {% if article_category.parents.all  %}
                <a data-toggle="collapse" data-parent="#accordian" href="#{{article_category.url_title}}">
                    <span class="pull-left"><i class="bx bx-plus"></i></span>
                    <a href="{% url 'article:articles_category' category=article_category.url_title %}">{{article_category.title}}</a>
                </a>
            {% else %}
                <a href="{% url 'article:articles_category' category=article_category.url_title %}">
                    {{article_category.title}}
                </a>
            {% endif %}



            {% if article_category.parents.all %}
                <div id="{{article_category.url_title}}" class="panel-collapse collapse">
                    <div class="panel-body">
                        
                        <ul>
                            {% for item in article_category.parents.all %}
                            
                                <li><a href="{% url 'article:articles_category' category=item.url_title %}">{{item.title}}</a></li>
                        
                            {% endfor %}
                        </ul>
                        
                    </div>
                </div>
            {% endif %}

        {% endfor %}
    </ul>
</div>